messages:
  start: "Здравствуйте! Меня зовут Smarty — цифровой помощник приемной комиссии института Smart. \nГотов ответить на все ваши вопросы. Напишите ваш вопрос в чат?"
keyboard:
  add_profile: "Меню"
  edit_profile: "..."
