messages:
  start: "Здравствуйте! Меня зовут — Smarty. Я цифровой помощник международного онлайн-института психологии Smart, созданный на базе искусственного интеллекта. Я отлично понимаю человеческую речь, поэтому можете общаться со мной, как с живым человеком.
\n\n
Я могу подобрать вам обучающую программу, рассказать подробнее об институте Smart или профессии психолога. Напишите ваш вопрос в чат."

keyboard:
  add_profile: "Меню"
  edit_profile: "..."
